stages:
  - lint

pre-commit:
  image: python:3.10
  stage: lint
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_REF_PROTECTED == "true"'
      when: always
    - when: never
  variables:
    PIP_DISABLE_PIP_VERSION_CHECK: "1"
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
    PIP_CACHE_DIR: ${CI_PROJECT_DIR}/.cache/pip
    RUFF_CACHE_DIR: ${CI_PROJECT_DIR}/.ruff_cache
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
      - ${PIP_CACHE_DIR}
      - ${RUFF_CACHE_DIR}
      - venv/
  before_script:
    - python -m venv venv
    - . venv/bin/activate
  script:
    - apt-get update && apt-get install -y jq
    - pip install pre-commit
    - 'CHANGED_FILES=$(curl --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/diffs" | jq -r ".[].new_path")'
    - echo "$CHANGED_FILES"
    - pre-commit run --files $CHANGED_FILES --show-diff-on-failure
